CREATE TABLE nyc_collisions (
    crash_date varchar,
	crash_time varchar,
	borough varchar,
	zip_code varchar,
	latitude double precision,
	longitude double precision,
	location varchar,
	on_street_name varchar,
	cross_street_name varchar,
	off_street_name varchar,
	number_of_persons_injured double precision,
	number_of_persons_killed double precision,
	number_of_pedestrians_injured integer,
	number_of_pedestrians_killed integer,
	number_of_cyclist_injured integer,
	number_of_cyclist_killed integer,
	number_of_motorist_injured integer,
	number_of_motorist_killed integer,
	contributing_factor_vehicle_1 varchar,
	contributing_factor_vehicle_2 varchar,
	contributing_factor_vehicle_3 varchar,
	contributing_factor_vehicle_4 varchar,
	contributing_factor_vehicle_5 varchar,
	collision_id integer,
	vehicle_type_code_1 varchar,
	vehicle_type_code_2 varchar,
	vehicle_type_code_3 varchar,
	vehicle_type_code_4 varchar,
	vehicle_type_code_5 varchar
)